### ISSUE TITLE
请问下，从论文中看rpnet不支持图中多车牌检测和识别？

### ISSUE THREAD

**Issue by dl8207531** [detectRecog/CCPD#18]
请问下，从论文中看rpnet不支持图中多车牌检测和识别？

**Comment by jiamei10605** [comment]
应该不支持

**Comment by wanglaotou** [comment]
最后3个rois整合concat到一起然后送到七个分类器中进行分类，所以不支持多车牌识别。

**Comment by dl8207531** [comment]
https://blog.csdn.net/42252343/article/details/96302574
