### ISSUE TITLE
about AdaptiveMaxPool2d

### ISSUE THREAD

**Issue by mmchen88** [detectRecog/CCPD#31]
你的 AdaptiveMaxPool2d和torch.nn.AdaptiveMaxPool2d有什么不同么？

**Comment by Fansgithub2019** [comment]
你能执行这一段代码吗？
self._backend.SpatialAdaptiveMaxPooling_updateOutput(
            self._backend.library_state, input, output, indices,
            self.out_w, self.out_h)
出现了NotImplementedError 错误
这个SpatialAdaptiveMaxPooling_updateOutput()是不是没有被定义。
你有解决办法吗

**Comment by HanZhizhi** [comment]
> 你的 AdaptiveMaxPool2d和torch.nn.AdaptiveMaxPool2d有什么不同么？

封装了一下，
`def adaptive_max_pool(input, size):
    return AdaptiveMaxPool2d(size[0], size[1])(input)`

**Comment by HanZhizhi** [comment]
> 你能执行这一段代码吗？
> self._backend.SpatialAdaptiveMaxPooling_updateOutput(
> self._backend.library_state, input, output, indices,
> self.out_w, self.out_h)
> 出现了NotImplementedError 错误
> 这个SpatialAdaptiveMaxPooling_updateOutput()是不是没有被定义。
> 你有解决办法吗

你好，我遇到了同样的问题，请问有没有解决呢。。

**Comment by songtao-ye** [comment]
> > 你能执行这一段代码吗？
> > self._backend.SpatialAdaptiveMaxPooling_updateOutput(
> > self._backend.library_state, input, output, indices,
> > self.out_w, self.out_h)
> > 出现了NotImplementedError 错误
> > 这个SpatialAdaptiveMaxPooling_updateOutput()是不是没有被定义。
> > 你有解决办法吗
> 
> 你好，我遇到了同样的问题，请问有没有解决呢。。

Torch1.0+ 用nn.AdaptiveMaxPool2d来代替就可以run
