### ISSUE TITLE
How do I download the data into Google Colab

### ISSUE THREAD

**Issue by THINK989** [detectRecog/CCPD#68]
Hello Authors,

I downloaded the data from google drive a few days back and now trying to train my model on it. But I worry it might fry my GPU since it is taking a lot of time to run on my local machine. It has already taken half of my day to run on just 5 epochs. I know I can't ask any more from since you guys have made such a big dataset public. I would really appreciate your help here.

I wanted to export the data to google colab to speed up training. I tried to search on this issue online but could not find a good response. If anyone can help me with this issue please help.

The download link seems to be https://drive.google.com/uc?id=1rdEsCUcIUaYOVRkx5IMTRNA7PcGMmSgc&export=download

Is there anything I can do with this to load the data directly into google colab?

Thank You

**Comment by pranavkantgaur** [comment]
Hi @THINK989,
Did you manage to download the dataset to Google collab?
